//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Int64 = require('node-int64');


export declare enum SessionState {
  Offline = 0,
  SettingConfig = 1,
  Building = 2,
  BuildDone = 3,
  StartFlashing = 4,
  DoneFlashing = 5,
  StartLoading = 6,
  DoneLoading = 7,
  StartAllLoaded = 8,
  DoneAllLoaded = 9,
  Running = 10,
  EndSession = 11,
  StartPartnerRegistryReset = 12,
  DonePartnerRegistryReset = 13,
  Terminate = 14,
  RestartAtOffline = 15,
  Disconnect = 16,
}

export declare enum LowLevelAction {
  kDontCallLowLevelGo = 0,
  kStartCPU = 1,
  kStartAllCPUs = 2,
  kPollingOnly = 3,
}

export declare enum CoreLowLevelResult {
  kFullStop = 0,
  kReportToKernel = 1,
  kSympathetic = 2,
  kGoAgain = 3,
  kTurnedZombie = 4,
  kError = 5,
  kIllegal = 6,
}

export declare enum WhatNext {
  kReturnFromDriverGo = 0,
  kLowLevelGoAgain = 1,
  kReturnError = 2,
  kReturnFromDriverGoAndStop = 3,
}

export declare enum CoreStatus {
  kCoreStopped = 0,
  kCoreRunning = 1,
  kCoreZombie = 2,
}

export declare enum Tools {
  EmbeddedWorkbench = 0,
  CSpyBat = 1,
  CSpyServer = 2,
  CSpyRuby = 3,
}

export declare class PartnerInformation {
  id: number;
  cspyConfiguration: SessionConfiguration;
  configuration: { [k: string]: string; };
  isAlive: boolean;

    constructor(args?: { id: number; cspyConfiguration: SessionConfiguration; configuration: { [k: string]: string; }; isAlive: boolean; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare class CoreInfo {
  id: number;
  name: string;
  status: DkCoreStatusConstants;
  statusString: string;
  pc: string;
  cc: string;
  partner: number;
  localCoreId: number;

    constructor(args?: { id: number; name: string; status: DkCoreStatusConstants; statusString: string; pc: string; cc: string; partner: number; localCoreId: number; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare class UnknownPartner extends Thrift.TException {
  id: number;

    constructor(args?: { id: number; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare class CoreRange {
  first: number;
  last: number;

    constructor(args?: { first: number; last: number; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare class Event {
  type: string;
  properties: { [k: string]: string; };

    constructor(args?: { type: string; properties?: { [k: string]: string; }; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare class EventBusRegistrationFailed extends Thrift.TException {
  message: string;
  type: number;

    constructor(args?: { message: string; type: number; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare class NumberOfCoresInfo {
  numberOfCores: number;
  localCores: number;
  localCoreOffset: number;

    constructor(args?: { numberOfCores: number; localCores: number; localCoreOffset: number; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare class FailedToStartPartner extends Thrift.TException {
  partner: number;
  message: string;

    constructor(args?: { partner: number; message: string; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare var AMP_VERSION: number;

export declare var CORES_REGISTRY_SERVICE: string;

export declare var PARTNER_REGISTRY_SERVICE: string;

export declare var EVENT_BUS_SERVICE: string;

export declare var SESSION_SYNCHRONIZER_SERVICE: string;

export declare var GATE_KEEPER_SERVICE: string;

export declare var MULTI_CORE_LOG_SERVICE: string;

export declare var SOFT_CTI_SERVICE: string;

export declare var CPU_STATUS_POLL_CONTROL_SERVICE: string;

export declare var DEBUGGER_STARTER_SERVICE: string;

export declare var PARTNER_REGISTRY_PARTNER_SET_EVENT: string;

export declare var PARTNER_REGISTRY_PARTNER_IS_ALIVE_EVENT: string;

export declare var PARTNER_REGISTRY_PARTNER_IS_DECEASED_EVENT: string;

export declare var PARTNER_REGISTRY_EVENT_PARTNER_ID: string;

export declare var CORES_REGISTRY_UPDATED_EVENT: string;

export declare var EVENT_SENDING_PARTNERID_KEY: string;

export declare var SESSION_SYNCHRONIZER_SYNCSTART_EVENT: string;

export declare var SESSION_SYNCHRONIZER_FROM_KEY: string;

export declare var SESSION_SYNCHRONIZER_TO_KEY: string;

export declare var SESSION_SYNCHRONIZER_SYNCSTART_SENDING_PARTNER_KEY: string;

export declare var SESSION_SYNCHRONIZER_SYNCCOMMIT_EVENT: string;

export declare var SESSION_SYNCHRONIZER_DEBUGGERSTART_EVENT: string;

export declare var SESSION_SYNCHRONIZER_DEBUGGERENDSESSION_EVENT: string;

export declare var SESSION_SYNCHRONIZER_DEBUGGERTERMINATE_EVENT: string;

export declare var SESSION_SYNCHRONIZER_DEBUGGERDISCONNECT_EVENT: string;

export declare var SESSION_SYNCHRONIZER_EVENT_PARTNER_ID: string;

export declare var EXEC_CONTROL_GO_EVENT: string;

export declare var EXEC_CONTROL_STOP_EVENT: string;

export declare var EXEC_CONTROL_MULTISTOP_EVENT: string;

export declare var EXEC_CONTROL_MULTIGO_EVENT: string;

export declare var EXEC_CONTROL_SET_RUNALL_EVENT: string;

export declare var EXEC_CONTROL_SET_RUNONE_EVENT: string;

export declare var EXEC_CONTROL_EVENT_CORE_KEY_PREFIX: string;

export declare var SOFT_CTI_STOP_ALL_EVENT: string;

export declare var SOFT_CTI_EVENT_CORE_KEY_PREFIX: string;

export declare var SOFT_CTI_EVENT_ID_KEY_PREFIX: string;

export declare var CPU_STATUS_POLL_CONTROL_DISABLE_EVENT: string;

export declare var CPU_STATUS_POLL_CONTROL_ENABLE_EVENT: string;

export declare var DEBUGGER_STARTER_TOOL_TO_START_KEY: string;

export declare var DEBUGKERNEL_EXEC_STARTED_EVENT: string;

export declare var DEBUGKERNEL_EXEC_STOPPED_EVENT: string;

export declare var DEBUGKERNEL_RESET_EVENT: string;

export declare var DEBUGKERNEL_BEGIN_SESSION_EVENT: string;

export declare var DEBUGKERNEL_END_SESSION_EVENT: string;

export declare var DEBUGKERNEL_MEMMOY_CHANGED_EVENT: string;

export declare var DEBUGKERNEL_SENDER: string;
