//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Int64 = require('node-int64');

import { crun } from "./crun_types";


/**
 * Service for presenting C-RUN messages to the user.
 */
export declare class Client {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  itemAdded(message: CRunMessage, partnerNamespace: string): Q.Promise<void>;

  itemAdded(message: CRunMessage, partnerNamespace: string, callback?: (data: void)=>void): void;

  itemUpdated(message: CRunMessage, partnerNamespace: string): Q.Promise<void>;

  itemUpdated(message: CRunMessage, partnerNamespace: string, callback?: (data: void)=>void): void;

  itemRemoved(index: number, partnerNamespace: string): Q.Promise<void>;

  itemRemoved(index: number, partnerNamespace: string, callback?: (data: void)=>void): void;

  updateAll(partnerNamespace: string): Q.Promise<void>;

  updateAll(partnerNamespace: string, callback?: (data: void)=>void): void;

  filtersChanged(partnerNamespace: string): Q.Promise<void>;

  filtersChanged(partnerNamespace: string, callback?: (data: void)=>void): void;
}
