//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');
import shared_ttypes = require('./shared_types');



declare enum EventId {
  kReloadWorkspace = 0,
  kReloadProject = 1,
  kReloadConfiguration = 2,
  kProjectAdded = 3,
  kConfigurationAdded = 4,
  kProjectRemoved = 5,
  kConfigurationRemoved = 6,
  kReloadTree = 7,
}

declare class ProjectManagerEvent {
  public eventId: EventId;
  public project: string;
  public configurations: string[];

    constructor(args?: { eventId: EventId; project: string; configurations: string[]; });
  read(input: Object): void;
  write(input: Object): void;
}

declare var EVENTMANAGER_ID: string;
