/// <reference path="HeartbeatService.d.ts" />
//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Int64 = require('node-int64');

import { ampsync } from "./ampsync_types";


export declare class Client extends HeartbeatService.Client {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  Fire(toBeFired: Event): Q.Promise<void>;

  Fire(toBeFired: Event, callback?: (data: void)=>void): void;

  RegisterWithVersion(clientLocation: ServiceLocation, myId: number, ampVersion: number): Q.Promise<void>;

  RegisterWithVersion(clientLocation: ServiceLocation, myId: number, ampVersion: number, callback?: (data: void)=>void): void;

  Register(clientLocation: ServiceLocation, myId: number): Q.Promise<void>;

  Register(clientLocation: ServiceLocation, myId: number, callback?: (data: void)=>void): void;
}
