//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Int64 = require('node-int64');


/**
 * Which icon to display in the message box
 */
export declare enum MsgIcon {
  kMsgIconInfo = 0,
  kMsgIconQuestion = 1,
  kMsgIconExclaim = 2,
  kMsgIconStop = 3,
}

/**
 * What set of buttons to use in the message box
 */
export declare enum MsgKind {
  kMsgOk = 0,
  kMsgOkCancel = 1,
  kMsgYesNo = 2,
  kMsgYesNoCancel = 3,
}

/**
 * Which button was used to dismiss the message box
 */
export declare enum MsgResult {
  kMsgResOk = 0,
  kMsgResCancel = 1,
  kMsgResYes = 2,
  kMsgResNo = 3,
}

/**
 * The type of dialog to open
 */
export declare enum FileDialogType {
  kOpen = 0,
  kSaveAs = 1,
}

/**
 * The set of allowed return types. kExistingFiles
 * allows returning multiple file
 */
export declare enum FileDialogReturnType {
  kAny = 0,
  kExistingFile = 1,
  kDirectory = 2,
  kExistingFiles = 3,
}

/**
 * The set of allowed options which the backend is expecting.
 */
export declare enum FileDialogOptions {
  kNoOverwritePrompt = 0,
  kFileMustExist = 1,
  kPathMustExist = 2,
  kAllowReturningReadOnlyFile = 3,
}

export declare enum GenericDialogReturnType {
  kOk = 0,
  kCancel = 1,
  kUnknown = 2,
}

/**
 * Small helper struct for filters. The display name is
 * the readable name of the filter and the files allowed
 * are listed in the filtering vector.
 */
export declare class FileDialogFilter {
  displayName: string;
  filtering: string[];

    constructor(args?: { displayName: string; filtering: string[]; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare class GenericDialogResults {
  type: GenericDialogReturnType;
  items: PropertyTreeItem;

    constructor(args?: { type: GenericDialogReturnType; items: PropertyTreeItem; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare var FRONTEND_SERVICE: string;
