//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Int64 = require('node-int64');

import { libsupport } from "./libsupport_types";


/**
 * This service redirects the I/O streams of the program being
 * debugged by C-SPY towards the environment hosting C-SPY itself.
 */
export declare class Client {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  /**
   * Request input from the terminal I/O console.
   */
  requestInputBinary(len: number): Q.Promise<string>;

  /**
   * Request input from the terminal I/O console.
   */
  requestInputBinary(len: number, callback?: (data: string)=>void): void;

  /**
   * @deprecated, use requestInputBinary instead
   */
  requestInput(len: number): Q.Promise<string>;

  /**
   * @deprecated, use requestInputBinary instead
   */
  requestInput(len: number, callback?: (data: string)=>void): void;

  /**
   * Handle output from the target program.
   */
  printOutputBinary(data: string): Q.Promise<void>;

  /**
   * Handle output from the target program.
   */
  printOutputBinary(data: string, callback?: (data: void)=>void): void;

  /**
   * @deprecated, use printOutputBinary instead
   */
  printOutput(data: string): Q.Promise<void>;

  /**
   * @deprecated, use printOutputBinary instead
   */
  printOutput(data: string, callback?: (data: void)=>void): void;

  /**
   * The target program has exited.
   */
  exit(code: number): Q.Promise<void>;

  /**
   * The target program has exited.
   */
  exit(code: number, callback?: (data: void)=>void): void;

  /**
   * The target program has aborted (i.e. called abort()).
   */
  reportAssert(file: string, line: string, message: string): Q.Promise<void>;

  /**
   * The target program has aborted (i.e. called abort()).
   */
  reportAssert(file: string, line: string, message: string, callback?: (data: void)=>void): void;
}
