//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Int64 = require('node-int64');


export declare enum LogSeverity {
  kDebug = -1,
  kUser = 0,
  kMinorInfo = 1,
  kInfo = 2,
  kWarning = 3,
  kError = 4,
  kAlert = 5,
  kSuper = 6,
}

export declare class SrcPos {
  row: number;
  col: number;
  valid: boolean;

    constructor(args?: { row: number; col: number; valid: boolean; });
  read(input: Object): void;
  write(input: Object): void;
}

/**
 * An entry in a log, matches IfLogServer::Entry
 */
export declare class LogEntry {
  category: string;
  sender: string;
  text: string;
  severity: LogSeverity;
  path: string;
  srcPos: SrcPos;
  srcEndPos: SrcPos;
  timestamp: Int64;
  entryId: Int64;
  isSubEntry: boolean;

    constructor(args?: { category: string; sender: string; text: string; severity: LogSeverity; path: string; srcPos: SrcPos; srcEndPos: SrcPos; timestamp: Int64; entryId: Int64; isSubEntry: boolean; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare var LOGSERVICE_ID: string;
