//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
if (typeof Int64 === 'undefined' && typeof require === 'function') {
  var Int64 = require('node-int64');
}


//HELPER FUNCTIONS AND STRUCTURES

var QuickWatch_evaluate_args = function(args) {
  this.expr = null;
  if (args) {
    if (args.expr !== undefined && args.expr !== null) {
      this.expr = args.expr;
    }
  }
};
QuickWatch_evaluate_args.prototype = {};
QuickWatch_evaluate_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.expr = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QuickWatch_evaluate_args.prototype.write = function(output) {
  output.writeStructBegin('QuickWatch_evaluate_args');
  if (this.expr !== null && this.expr !== undefined) {
    output.writeFieldBegin('expr', Thrift.Type.STRING, 1);
    output.writeString(this.expr);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var QuickWatch_evaluate_result = function(args) {
};
QuickWatch_evaluate_result.prototype = {};
QuickWatch_evaluate_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

QuickWatch_evaluate_result.prototype.write = function(output) {
  output.writeStructBegin('QuickWatch_evaluate_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var QuickWatchClient = exports.Client = function(input, output) {
  this.input = input;
  this.output = (!output) ? input : output;
  this.seqid = 0;
};
Thrift.inherits(QuickWatchClient, ListWindowBackendClient);

QuickWatchClient.prototype.evaluate = function(expr, callback) {
  this.send_evaluate(expr, callback); 
};

QuickWatchClient.prototype.send_evaluate = function(expr, callback) {
  var params = {
    expr: expr
  };
  var args = new QuickWatch_evaluate_args(params);
  try {
    this.output.writeMessageBegin('evaluate', Thrift.MessageType.ONEWAY, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      this.output.getTransport().flush(true, null);
      callback();
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};
