//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Int64 = require('node-int64');

import { ServiceRegistry } from "./ServiceRegistry_types";


export declare class Client {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  servicesChanged(services: { [k: string]: ServiceLocation; }): Q.Promise<void>;

  servicesChanged(services: { [k: string]: ServiceLocation; }, callback?: (data: void)=>void): void;
}
