//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Int64 = require('node-int64');


export declare class ServiceConfig {
  name: string;
  libraryName: string;
  spawnNewProcess: boolean;
  startupEntryPoint: string;
  shutdownEntryPoint: string;
  registerInLauncher: boolean;

    constructor(args?: { name: string; libraryName: string; spawnNewProcess: boolean; startupEntryPoint: string; shutdownEntryPoint: string; registerInLauncher: boolean; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare class LauncherConfig {
  useInternalRegistry: boolean;
  externalRegistryLocation: ServiceLocation;
  preferredTransports: Transport[];

    constructor(args?: { useInternalRegistry: boolean; externalRegistryLocation: ServiceLocation; preferredTransports: Transport[]; });
  read(input: Object): void;
  write(input: Object): void;
}

export declare var SERVICE_MANAGER_SERVICE: string;
