/// <reference path="ListWindowBackend.d.ts" />
//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Int64 = require('node-int64');

import { listwindow } from "./listwindow_types";


export declare class Client extends ListWindowBackend.Client {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  setStack(name: string): Q.Promise<void>;

  setStack(name: string, callback?: (data: void)=>void): void;

  getStack(): Q.Promise<string>;

  getStack(callback?: (data: string)=>void): void;

  getStacks(): Q.Promise<string[]>;

  getStacks(callback?: (data: string[])=>void): void;

  getBarTooltip(): Q.Promise<string>;

  getBarTooltip(callback?: (data: string)=>void): void;

  getBarInfo(): Q.Promise<StackBarInfo>;

  getBarInfo(callback?: (data: StackBarInfo)=>void): void;

  getStackSettings(): Q.Promise<StackSettings>;

  getStackSettings(callback?: (data: StackSettings)=>void): void;
}
